#!/bin/sh

/bin/busybox --install -s

[ -d /dev ] || mkdir -m 0755 /dev
[ -d /root ] || mkdir --mode=0700 /root
[ -d /sys ] || mkdir /sys
[ -d /proc ] || mkdir /proc
[ -d /tmp ] || mkdir /tmp
mkdir -p /var/lock
mount -t sysfs none /sys -onodev,noexec,nosuid
mount -t proc none /proc -onodev,noexec,nosuid

mknod /dev/zero c 1 5
mknod /dev/null c 1 3

#mknod /dev/tty c 5 0
#mknod /dev/console c 5 1
#mknod /dev/ptmx c 5 2
#mknod /dev/pts c 5 2

#mknod /dev/tty0 c 4 0
#mknod /dev/tty1 c 4 1

echo "/sbin/mdev" > /proc/sys/kernel/hotplug

echo "Creating devices"
/sbin/mdev -s

modprobe e1000

exec /sbin/init
